site_name: The Pipsqueakery FAQs

nav:
  - Home: index.md
  - Adopt: adopt.md
  - Animal Care by Species: 
    - care/chinchillas.md
    - care/guineapigs.md
    - care/hamsters.md
    - care/hedgehogs.md
    - care/mice.md
    - care/rabbits.md
    - care/rats.md
  - Foster: fostering.md
  - Vets: vets.md
  - Help: programs.md
  - Surrender: surrender.md

